version: '3'

services:
  api:
    build: ./
    restart: always
    container_name: api
    depends_on:
      - db
    networks:
      - nodenet
    expose:
      - 3000
    command: sh -c '/usr/bin/wait-for http://db:3306 -- node ./index.js'
  db:
    image: mysql
    restart: always
    container_name: db
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'fullcycle'
    networks:
      - nodenet
    expose:
      - 3306
    volumes:
      - volume-node:/var/lib/mysql
  web:
    build:
      context: ./
      dockerfile: Dockerfile_nginx
    restart: always
    container_name: web
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - api
    command: sh -c '/usr/bin/wait-for http://api:3000 -- nginx -g "daemon off;"'
networks:
  nodenet:
volumes:
  volume-node: